### PR TITLE
Add new get_rosters function

### PR DESCRIPTION
**Pull request by mrcaseb**
* Added new and more efficient function 'get_rosters' in scrape_rosters.R
* Added observation 'Las Vegas Raiders' in nflteams.rda
* Added variable 'teamId' in nflteams.rda which is required for the new get_rosters function

### CODE REVIEW

**Comment by mrcaseb** [comment]
This pull request is related to the closed issue #157

**Comment by mrcaseb** [comment]
Have you had time to look at the function or decide whether to add it? If no interest exists I would possibly publish elsewhere.

**Comment by eopage18** [comment]
Is there a way to get rosters for all teams and all positions for a given season?

**Comment by mrcaseb** [comment]
Guys I'm closing this because it is implemented elsewhere.

**Pull request closed without merging**
